# Problem initialization: eggcarton, enumerate (testing), constant (testing)
problem: eggcarton

# Iteration, error, and output control
max_iterations: 100
error_tolerance: 1.0e-6
log_frequency: 1

# Vcycle control
vcycle_direct: 1
vcycle_pre: 5
vcycle_post: 5

# Geometry
coords:
  - [0.0, 0.0]
  - [1.0, 1.0]
